#!/usr/bin/python3
"""
This script defines the bootstrap used in https://github.com/sheatsley/dotfiles
"""

import os
import subprocess
import threading


def install_brew_packages(file=".brewbundle"):
    """ """
    env = os.environ.copy()
    print("Installing brew packages...")
    subprocess.run(
        args=["brew", "bundle", "install", "--cleanup"],
        check=True,
        env=env | {"HOMEBREW_BUNDLE_FILE": file},
    )
    return None


def install_homebrew(
    url="https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh",
):
    """ """
    print("Installing brew...")
    env = os.environ.copy()
    filename = url.split("/").pop()
    subprocess.run(args=["curl", "-o", f"/tmp/{filename}", "-fssSL", url], check=True)
    subprocess.run(
        args=["/bin/bash", f"/tmp/{filename}"],
        check=True,
        env=env | {"NONINTERACTIVE": "1"},
    )
    subprocess.run(
        args=["echo", ">>", "~/.zprofile"],
        check=True,
    )
    homebrew_path = subprocess.run(
        args=["/opt/homebrew/bin/brew", "shellenv"], capture_output=True, check=True
    ).stdout.decode(encoding="utf-8")
    subprocess.run(
        args=["echo", homebrew_path, ">>" "~/.zprofile"],
        check=True,
    )
    subprocess.run(
        args=["source", "~/.zprofile"],
        check=True,
    )
    return None


def install_pip_packages(file=".pip"):
    """ """
    print("Installing python modules...")
    env = os.environ.copy()
    subprocess.run(
        args=["pip3", "install", "--upgrade", "pip"],
        check=True,
        env=env | {"PIP_NO_INPUT": "1"},
    )
    subprocess.run(
        args=["pip3", "install", "--upgrade", "--requirement", file],
        check=True,
        env=env | {"PIP_NO_INPUT": "1"},
    )
    return None


def install_submodules():
    """ """
    print("Installing yadm submodules...")
    subprocess.run(
        args=[
            "yadm",
            "submodule",
            "update",
            "--init",
            "--recursive",
            "--remote",
            "--rebase",
        ],
        check=True,
    )
    return None


def install_vim_plugins():
    """ """
    print("Installing vim plugins...")
    subprocess.run(args=["vim", "+call mkdp#util#install()", "+qall"], check=True)
    subprocess.run(args=["vim", "+Copilot setup", "+qall"], check=True)
    subprocess.run(args=["vim", ".vimrc", "+helptags ALL", "+qall"], check=True)
    return None


def refresh_sudo(complete, interval=60):
    """ """
    print("Refreshing sudo credentials...")
    subprocess.run(args=["sudo", "-v"], check=True)
    while not complete.is_set():
        subprocess.run(args=["sudo", "-v"], check=True)
        complete.wait(interval)
    return None


def set_computer_name():
    """ """
    print("Enter computer name:")
    name = input()
    subprocess.run(args=["sudo", "scutil", "--set", "ComputerName", name], check=True)
    subprocess.run(args=["sudo", "scutil", "--set", "HostName", name], check=True)
    subprocess.run(
        args=["sudo", "scutil", "--set", "LocalHostName", name.replace(" ", "-")],
        check=True,
    )
    return None


def set_public_key(key="D97737F91189673C"):
    """ """
    print(f"Adding GPG public key {key} to keyring and setting trust to ulimate...")
    subprocess.run(
        args=["gpg", "--card-edit", "--command-fd", "0"],
        check=True,
        text=True,
        input="fetch\n",
    )
    subprocess.run(
        args=["gpg", "--command-fd", "0", "--edit-key", key, "trust"],
        check=True,
        input=b"5\ny\n",
    )
    return None


def set_git_crypt(key="D97737F91189673C"):
    """ """
    print(f"Decrypting files with {key}...")
    subprocess.run(args=["yadm", "crypt", "unlock"], check=True)
    return None


def set_github_repos(directory="repos", file=".gitrepos", gitlab=False, jobs=8):
    """ """
    print("Setting up GitHub repos...")
    with open(file, "r") as f:
        for repo in f.readlines():
            owner, name = repo.strip().split("/")
            if not os.path.isdir(f"{directory}/{name}"):
                subprocess.run(
                    args=[
                        "git",
                        "clone",
                        f"git@github.com:{owner}/{name}.git",
                        f"{directory}/{name}",
                    ],
                    check=True,
                )
            else:
                subprocess.run(
                    args=[
                        "git",
                        "-C",
                        f"{directory}/{name}",
                        "pull",
                        "--jobs",
                        str(jobs),
                        "--recurse-submodules",
                    ],
                    check=True,
                )
            if gitlab:
                subprocess.run(
                    args=[
                        "git",
                        "-C",
                        f"{directory}/{name}",
                        "submodule",
                        "update",
                        "--init",
                        "--recursive",
                        "--jobs",
                        str(jobs),
                    ],
                    check=True,
                )
    return None


def set_gpg_agent():
    """ """
    print("Setting GPG agent...")
    env = os.environ.copy()
    os.environ["PATH"] = (
        subprocess.run(
            args=["/usr/libexec/path_helper"], capture_output=True, check=True
        )
        .stdout.decode(encoding="utf-8")
        .strip()
        .split(";")
        .pop(0)
        .split("=")
        .pop()
        .strip('"')
    )
    os.environ["GPG_TTY"] = (
        subprocess.run(args=["tty"], capture_output=True, check=True)
        .stdout.decode(encoding="utf-8")
        .strip()
    )
    os.environ["SSH_AUTH_SOCK"] = (
        subprocess.run(
            args=["gpgconf", "--list-dirs", "agent-ssh-socket"],
            capture_output=True,
            check=True,
        )
        .stdout.decode(encoding="utf-8")
        .strip()
    )
    subprocess.run(args=["gpgconf", "--launch", "gpg-agent"], check=True, env=env)
    subprocess.run(
        args=["gpg-connect-agent", "updatestartuptty", "/bye"], check=True, env=env
    )
    return None


def set_iterm2():
    """ """
    print("Configuring iTerm2 profile...")
    subprocess.run(
        args=[
            "defaults",
            "write",
            "com.googlecode.iterm2",
            "PrefsCustomFolder",
            "$HOME/.iterm2",
        ],
        check=True,
    )
    subprocess.run(
        args=[
            "defaults",
            "write",
            "com.googlecode.iterm2",
            "LoadPrefsFromCustomFolder",
            "-int",
            "1",
        ],
        check=True,
    )
    return None


def set_macos_defaults(file=".macos"):
    """ """
    print("Setting macOS defaults...")
    subprocess.run(args=["sh", file], check=True)
    return None


def set_yadm_repo():
    """ """
    print("Changing remote url of yadm repo...")
    reponame = (
        subprocess.run(
            args=["yadm", "remote", "get-url", "origin"],
            capture_output=True,
            check=True,
        )
        .stdout.decode(encoding="utf-8")
        .strip()
        .split(":")
        .pop()
    )
    subprocess.run(args=["yadm", "remote", "set-url", "origin", reponame], check=True)
    return None


def check(key="D97737F91189673C"):
    """ """
    os.chdir(os.path.expanduser("~"))
    complete = threading.Event()
    sudo_thread = threading.Thread(args=(complete,), target=refresh_sudo)
    tasks = []
    names = []
    for pref in "ComputerName", "HostName", "LocalHostName":
        names.append(
            subprocess.run(args=["scutil", "--get", pref], capture_output=True)
            .stdout.decode(encoding="utf-8")
            .strip()
            .replace("-", " ")
        )
    if names[0] != names[1] or names[0] != names[2]:
        tasks.append(set_computer_name)
    if subprocess.run(args=["type", "brew"], stdout=subprocess.DEVNULL).returncode != 0:
        tasks.append(install_homebrew)
    tasks.append(install_brew_packages)
    tasks.append(install_pip_packages)
    try:
        assert "ultimate" in subprocess.run(
            args=["gpg", "-k", key], capture_output=True, check=True
        ).stdout.decode(encoding="utf-8")
    except:
        tasks.append(set_public_key)
    try:
        assert (
            subprocess.run(
                args=["yadm", "remote", "get-url", "origin"],
                capture_output=True,
                check=True,
            )
            .stdout.decode(encoding="utf-8")
            .startswith("http")
        )
    except:
        tasks.append(set_yadm_repo)
    if (
        not subprocess.run(
            args=["grep", "-qs", r"\x00GITCRYPT", ".gitrepos"]
        ).returncode
        != 0
    ):
        tasks.append(set_git_crypt)
    if (
        subprocess.run(args=["ssh-add", "-l"], stdout=subprocess.DEVNULL).returncode
        != 0
    ):
        tasks.append(set_gpg_agent)
    try:
        assert subprocess.run(
            args=["tailscale", "status"], stdout=subprocess.DEVNULL, timeout=2
        ).returncode
        gitlab = True
    except:
        gitlab = False
    tasks.append(set_github_repos)
    tasks.append(install_submodules)
    tasks.append(install_vim_plugins)
    tasks.append(set_iterm2)
    tasks.append(set_macos_defaults)
    sudo_thread.start()
    for task in tasks:
        if task == set_github_repos:
            task(gitlab=gitlab)
        else:
            task()
    complete.set()
    sudo_thread.join()
    return None


if __name__ == "__main__":
    """
    TODO
    - Use text=True to avoid decoding stdout (standardize args)
    - Don't run subtask *only if* main task check fails (if main task fails, who cares)
    - Add environment variables to os.environ
    - Prompt to give terminal full disk access
    - Declare commands as strings and use split when passing to subprocess.run
    """
    check()
    raise SystemExit(0)
